Fix check for PL SysMon
Xilinx/platformstats pull request #7
Opened 2024-10-23 17:27 UTC by vshpatel

2024-10-23 17:27 UTC, msreeram-xilinx commented
LICENSE CHECKS: 
Modified Files:
src/xlnx_platformstats.c: No License Change
License Check is Passed

2024-10-23 17:30 UTC, chkohn requested changes
see inline.

@pallav-xlnx  can you please review and merge?

2024-10-23 17:30 UTC, chkohn commented on src/xlnx_platformstats.c
> +		if (PL_TEMP_avg == -280226) {
prob better to use a macro here and a comment that explains what this magic value is

2024-10-23 17:57 UTC, msreeram-xilinx commented
LICENSE CHECKS: 
Modified Files:
src/xlnx_platformstats.c: No License Change
License Check is Passed

2024-10-25 00:07 UTC, pallav-xlnx approved these changes

2024-10-28 18:42 UTC, merged